/*
 *
 * Make sure you don't change anything
 * In this file. There are some notes
 * to help you understand what is happening
 * but you do not need to read them all to
 * complete the lab. 
 *
 */

/*

In node, when you export a method like:

```
exports.getOrCreateUser = // ....
```

you can import it with the following syntax:

```
const { getOrCreateUser } = require('path/to/this/file')
```

*/

const User = require('../models/User')

/**
 * Grabs a user asynchronously from MongoDB
 * @param profile - The profile of the user to get as generated by passport
 * @returns - An object representation of the user document in the database
 */
exports.getOrCreateUser = async function(profile) {
		let user = await User.findOne({Email: profile.emails[0].value})
		if (!user) {
      user = new User({
        Id: profile.id,
        Email: profile.emails[0].value,
      })
      await user.save()
		}
		return user
}

// This method is a middleware that I made that just checks if there's a
// `user` object on the `req` object. Passport creates the user object
// when you log in, so if you aren't logged in, then it'll just send a
// 401 (Unauthorized) to your client.
exports.authenticate = (req, res, next) => {
	if (req.user) next()
	else res.sendStatus(401)
}
